name: Build ROCm

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ROCM_VERSION: 6.2.2
  GPU_ARCHS: gfx900

jobs:
  Build:
    strategy:
        matrix:
            version: [20, 22, 24]
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
          remove-large-packages: true
          remove-cached-tools: true
          verbose: false
      - name: Join volumes
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 15360

      - name: Clone dependent repositories
        run: |
            mkdir -p ~/.bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
            chmod a+rx ~/.bin/repo

            ~/.bin/repo init -u http://github.com/ROCm/ROCm.git -b roc-6.2.x -m tools/rocm-build/rocm-${ROCM_VERSION}.xml --depth 1
            ~/.bin/repo sync
            cd rocm_bandwidth_test && git fetch --unshallow
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          path: ROCm

      - name: Pull docker image
        run: docker pull rocm/rocm-build-ubuntu-${{matrix.version}}.04:6.2
 
      - name: Make ROCm
        run: |
          docker run \
            -e ROCM_VERSION=${ROCM_VERSION} \
            -e GPU_ARCHS=${GPU_ARCHS} \
            -e CCACHE_DIR=$HOME/.ccache \
            -e CCACHE_ENABLED=true \
            -e DOCK_WORK_FOLD=/src \
            -w /src \
            -v $PWD:/src \
            -v /etc/passwd:/etc/passwd \
            -v /etc/shadow:/etc/shadow \
            -v ${HOME}/.ccache:${HOME}/.ccache \
            -u $(id -u):$(id -g) \
            rocm/rocm-build-ubuntu-${{matrix.version}}.04:6.2 \
            make -f ROCm/tools/rocm-build/ROCm.mk -j ${NPROC:-$(($(nproc) * 2))} all
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ROCm packages for Ubuntu ${{matrix.version}}.04
            path: out/ubuntu-${{matrix.version}}.04/${{matrix.version}}.04/deb
            retention-days: 3
      - name: Archive logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: Build logs for Ubuntu ${{matrix.version}}.04
            path: out/ubuntu-${{matrix.version}}.04/${{matrix.version}}.04/logs
            retention-days: 3
      
